@files = (
	['//property[propertyName="ui_forms"]/propertySheet/property[propertyName="IISCreateConfigForm"]/value'  , 'IISCreateConfigForm.xml'],
	['//property[propertyName="ui_forms"]/propertySheet/property[propertyName="IISEditConfigForm"]/value'  , 'IISEditConfigForm.xml'],

	['//property[propertyName="http_matchers"]/value', 'matchers/httpMatchers.pl'],
	['//property[propertyName="iisreset_matchers"]/value', 'matchers/iisresetMatchers.pl'],
	['//property[propertyName="net_matchers"]/value', 'matchers/netMatchers.pl'],
	['//property[propertyName="sitescript_matchers"]/value', 'matchers/siteScriptMatchers.pl'],
	['//property[propertyName="startwebserver_matchers"]/value', 'matchers/startWebServerMatchers.pl'],
	['//property[propertyName="continuewebserver_matchers"]/value', 'matchers/continueWebServerMatchers.pl'],
	['//property[propertyName="pausewebserver_matchers"]/value', 'matchers/pauseWebServerMatchers.pl'],
	['//property[propertyName="stopwebserver_matchers"]/value', 'matchers/stopWebServerMatchers.pl'],
	['//property[propertyName="enablewebapp_matchers"]/value', 'matchers/enableWebApplicationMatchers.pl'],
	['//property[propertyName="disablewebapp_matchers"]/value', 'matchers/disableWebApplicationMatchers.pl'],
	['//property[propertyName="startapppool_matchers"]/value', 'matchers/startAppPoolMatchers.pl'],
	['//property[propertyName="stopapppool_matchers"]/value', 'matchers/stopAppPoolMatchers.pl'],
	['//property[propertyName="createapppool_matchers"]/value', 'matchers/createAppPoolMatchers.pl'],
	['//property[propertyName="recycleapppool_matchers"]/value', 'matchers/recycleAppPoolMatchers.pl'],
	['//property[propertyName="unloadapp_matchers"]/value', 'matchers/unloadAppMatchers.pl'],
	['//property[propertyName="deletewebapp_matchers"]/value', 'matchers/deleteWebApplicationMatchers.pl'],
	['//property[propertyName="createvirtualdirectory2_matchers"]/value', 'matchers/createVirtualDirectory2Matchers.pl'],
	['//property[propertyName="createwebsite2_matchers"]/value', 'matchers/createWebSite2Matchers.pl'],
	['//property[propertyName="createwebapp_matchers"]/value', 'matchers/createWebApplicationMatchers.pl'],

	['//property[propertyName="IISServer.pm"]/value', 'agent/lib/IISServer.pm'],

	['//procedure[procedureName="StartServer"]/step[stepName="StartServer"]/command' , 'server/startServer.pl'],
	['//procedure[procedureName="StopServer"]/step[stepName="StopServer"]/command' , 'server/stopServer.pl'],
	['//procedure[procedureName="CreateWebSite"]/step[stepName="CreateWebSite"]/command' , 'server/createWebSite.pl'],
	['//procedure[procedureName="DeleteWebSite"]/step[stepName="DeleteWebSite"]/command' , 'server/deleteWebSite.pl'],
	['//procedure[procedureName="PauseWebSite"]/step[stepName="PauseWebSite"]/command' , 'server/pauseWebSite.pl'],
	['//procedure[procedureName="StartWebSite"]/step[stepName="StartWebSite"]/command' , 'server/startWebSite.pl'],
	['//procedure[procedureName="StopWebSite"]/step[stepName="StopWebSite"]/command' , 'server/stopWebSite.pl'],
	['//procedure[procedureName="CreateVirtualDirectory"]/step[stepName="CreateVirtualDirectory"]/command' , 'server/createVirtualDirectory.pl'],
	['//procedure[procedureName="CreateVirtualDirectory2"]/step[stepName="CreateVirtualDirectory"]/command' , 'server/createVirtualDirectory2.pl'],
	['//procedure[procedureName="DeleteVirtualDirectory"]/step[stepName="DeleteVirtualDirectory"]/command' , 'server/deleteVirtualDirectory.pl'],
	['//procedure[procedureName="ResetServer"]/step[stepName="ResetServer"]/command' , 'server/resetServer.pl'],
	['//procedure[procedureName="CheckServerStatus"]/step[stepName="CheckServerStatus"]/command' , 'server/checkServerStatus.pl'],
	['//procedure[procedureName="StartIISServices"]/step[stepName="StartIISServices"]/command' , 'server/startIISService.pl'],
	['//procedure[procedureName="StopIISServices"]/step[stepName="StopIISServices"]/command' , 'server/stopIISService.pl'],
	['//procedure[procedureName="DeployCopy"]/step[stepName="Deploy"]/command' , 'server/deployCopy.pl'],
	['//procedure[procedureName="GetWebSiteIDs"]/step[stepName="GetWebSiteIDs"]/command' , 'server/getWebSiteIDs.pl'],
	['//procedure[procedureName="GetWebSiteStatus"]/step[stepName="GetStatus"]/command' , 'server/getWebSiteStatus.pl'],
	['//procedure[procedureName="GetVirtualDirectories"]/step[stepName="GetVirtualDirectories"]/command' , 'server/getVirtualDirs.pl'],
	['//procedure[procedureName="CreateWebApplication"]/step[stepName="CreateWebApplication"]/command' , 'server/createWebApplication.pl'],
	['//procedure[procedureName="ResumeWebSite"]/step[stepName="ResumeWebSite"]/command' , 'server/continueWebServer.pl'],
	['//procedure[procedureName="EnableWebApplication"]/step[stepName="EnableWebApplication"]/command' , 'server/enableWebApplication.pl'],
	['//procedure[procedureName="DisableWebApplication"]/step[stepName="DisableWebApplication"]/command' , 'server/disableWebApplication.pl'],
	['//procedure[procedureName="DeleteWebApplication"]/step[stepName="DeleteWebApplication"]/command' , 'server/deleteWebApplication.pl'], 
	['//procedure[procedureName="UnloadApp"]/step[stepName="UnloadApp"]/command' , 'server/unloadApp.pl'], 
	['//procedure[procedureName="StartAppPool"]/step[stepName="StartAppPool"]/command' , 'server/startAppPool.pl'],
	['//procedure[procedureName="StopAppPool"]/step[stepName="StopAppPool"]/command' , 'server/stopAppPool.pl'],
	['//procedure[procedureName="CreateAppPool"]/step[stepName="CreateAppPool"]/command' , 'server/createAppPool.pl'],
	['//procedure[procedureName="RecycleAppPool"]/step[stepName="RecycleAppPool"]/command' , 'server/recycleAppPool.pl'],
	['//procedure[procedureName="CreateWebSite2"]/step[stepName="CreateWebSite"]/command' , 'server/createWebSite2.pl'],
	['//procedure[procedureName="StartIISServices"]/step[stepName="StartIISServices"]/command' , 'server/startIISService.pl'],
	['//procedure[procedureName="StopIISServices"]/step[stepName="StopIISServices"]/command' , 'server/stopIISService.pl'],

	['//procedure[procedureName="CreateConfiguration"]/step[stepName="CreateConfiguration"]/command' , 'conf/createcfg.pl'],
	['//procedure[procedureName="CreateConfiguration"]/step[stepName="CreateAndAttachCredential"]/command' , 'conf/createAndAttachCredential.pl'],
	['//procedure[procedureName="DeleteConfiguration"]/step[stepName="DeleteConfiguration"]/command' , 'conf/deletecfg.pl'],

	['//property[propertyName="ec_setup"]/value', 'ec_setup.pl'],

	['//procedure[procedureName="StartServer"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'forms/IISStartServerForm.xml'],
	['//procedure[procedureName="StopServer"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'forms/IISStopServerForm.xml'],
	['//procedure[procedureName="CreateAppPool"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'forms/IISCreateAppPoolForm.xml'],
	['//procedure[procedureName="CreateVirtualDirectory"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'forms/IISCreateVirtualDirectoryForm.xml'],
	['//procedure[procedureName="CreateWebSite"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'forms/IISCreateWebSiteForm.xml'],
	['//procedure[procedureName="CreateVirtualDirectory2"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'forms/IISCreateVirtualDirectory2Form.xml'],
	['//procedure[procedureName="CreateWebSite2"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'forms/IISCreateWebSite2Form.xml'],
	['//procedure[procedureName="StartAppPool"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'forms/IISStartAppPoolForm.xml'],
	['//procedure[procedureName="CheckServerStatus"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'forms/IISCheckServerStatusForm.xml'],
	['//procedure[procedureName="CreateWebApplication"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'forms/IISCreateWebApplicationForm.xml'],
	['//procedure[procedureName="DeleteVirtualDirectory"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'forms/IISDeleteVirtualDirectoryForm.xml'],
	['//procedure[procedureName="DeleteWebSite"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'forms/IISDeleteWebSiteForm.xml'],	
	['//procedure[procedureName="DeployCopy"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'forms/IISDeployCopyForm.xml'],
	['//procedure[procedureName="GetVirtualDirectories"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'forms/IISGetVirtualDirectoriesForm.xml'],
	['//procedure[procedureName="GetWebSiteIDs"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'forms/IISGetWebSiteIDsForm.xml'],
	['//procedure[procedureName="GetWebSiteStatus"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'forms/IISGetWebSiteStatusForm.xml'],
	['//procedure[procedureName="PauseWebSite"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'forms/IISPauseWebSiteForm.xml'],
	['//procedure[procedureName="RecycleAppPool"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'forms/IISRecycleAppPoolForm.xml'],
	['//procedure[procedureName="ResetServer"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'forms/IISResetServerForm.xml'],
	['//procedure[procedureName="ResumeWebSite"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'forms/IISResumeWebSiteForm.xml'],
	['//procedure[procedureName="StartWebSite"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'forms/IISStartWebSiteForm.xml'],
	['//procedure[procedureName="StopAppPool"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'forms/IISStopAppPoolForm.xml'],
	['//procedure[procedureName="StopWebSite"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'forms/IISStopWebSiteForm.xml'],	
	['//procedure[procedureName="StopIISServices"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'forms/IISStopIISServicesForm.xml'],	
	['//procedure[procedureName="StartIISServices"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'forms/IISStartIISServicesForm.xml'],	

);
